"""Initial migration

Revision ID: 543ff2f94c66
Revises: 
Create Date: 2025-09-06 16:12:46.780909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543ff2f94c66'
down_revision = None
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rides')
    op.drop_table('sms_codes')
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_table('reservations')
    op.drop_table('user_stats')
    op.drop_table('recurring_rides')
    op.drop_table('blocked_users')
    op.drop_table('ratings')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ride_id', sa.INTEGER(), nullable=False),
    sa.Column('rater_id', sa.INTEGER(), nullable=False),
    sa.Column('rated_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['rated_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocked_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('blocker_id', sa.INTEGER(), nullable=False),
    sa.Column('blocked_id', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_rides',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('from_location', sa.VARCHAR(), nullable=False),
    sa.Column('to_location', sa.VARCHAR(), nullable=False),
    sa.Column('departure_time', sa.VARCHAR(), nullable=False),
    sa.Column('days_of_week', sa.VARCHAR(), nullable=False),
    sa.Column('available_seats', sa.INTEGER(), nullable=True),
    sa.Column('price_per_person', sa.INTEGER(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('total_rides', sa.INTEGER(), nullable=True),
    sa.Column('total_distance', sa.FLOAT(), nullable=True),
    sa.Column('co2_saved', sa.FLOAT(), nullable=True),
    sa.Column('money_saved', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ride_id', sa.INTEGER(), nullable=False),
    sa.Column('passenger_id', sa.INTEGER(), nullable=False),
    sa.Column('seats_reserved', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.Column('total_rides', sa.INTEGER(), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ride_id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_codes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rides',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('from_location', sa.VARCHAR(), nullable=False),
    sa.Column('to_location', sa.VARCHAR(), nullable=False),
    sa.Column('departure_time', sa.VARCHAR(), nullable=False),
    sa.Column('available_seats', sa.INTEGER(), nullable=True),
    sa.Column('price_per_person', sa.INTEGER(), nullable=True),
    sa.Column('route_waypoints', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
