
"""empty message

Revision ID: 837737ab982c
Revises: b999ff017ce6
Create Date: 2025-09-06 11:27:27.849253+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '837737ab982c'
down_revision = 'b999ff017ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.alter_column('departure_time',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               postgresql_using='departure_time::timestamp without time zone',
               existing_nullable=False)

    with op.batch_alter_table('recurring_rides', schema=None) as batch_op:
        batch_op.alter_column('departure_time',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               postgresql_using='departure_time::timestamp without time zone',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_rides', schema=None) as batch_op:
        batch_op.alter_column('departure_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.alter_column('departure_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
