import os\nimport subprocess\nimport sys\nimport shutil\nimport json\nimport argparse\n\nNODE_APP_DIR = "node_app"\nSERVER_FILE = "server.js"\nPACKAGE_JSON_FILE = "package.json"\nPORT = 3000\n\n# Templates for Node.js files - embedded for simplicity\nSERVER_JS_TEMPLATE = """\nconst express = require('express');\nconst app = express();\nconst port = process.env.PORT || %d;\n\napp.get('/', (req, res) => {\n  res.send('Hello from Express.js! This server was set up by a Python script.');\n});\n\napp.get('/api', (req, res) => {\n  res.json({ message: 'This is an API endpoint from Express.js!' });\n});\n\napp.listen(port, () => {\n  console.log(`Express.js server listening at http://localhost:${port}`);\n});\n""" % PORT\n\nPACKAGE_JSON_TEMPLATE = """\n{\n  "name": "my-express-app",\n  "version": "1.0.0",\n  "description": "A simple Express.js application, managed by a Python script.",\n  "main": "%s",\n  "scripts": {\n    "start": "node %s"\n  },\n  "keywords": [\n    "express",\n    "node",\n    "python-managed"\n  ],\n  "author": "Python Manager",\n  "license": "ISC",\n  "dependencies": {}\n}\n""" % (SERVER_FILE, SERVER_FILE)\n\ndef check_nodejs_npm():\n    """Checks if Node.js and npm are installed."""\n    print("Checking for Node.js and npm...")\n    try:\n        subprocess.run(["node", "-v"], check=True, capture_output=True, text=True)\n        subprocess.run(["npm", "-v"], check=True, capture_output=True, text=True)\n        print("Node.js and npm are installed.")\n        return True\n    except (subprocess.CalledProcessError, FileNotFoundError):\n        print("\
Error: Node.js or npm is not installed. Please install them to proceed.")\n        print("Download Node.js from https://nodejs.org/en/download/")\n        return False\n\ndef setup_nodejs_app():\n    """Creates the Node.js application directory and files, installs dependencies."""\n    if not check_nodejs_npm():\n        sys.exit(1)\n\n    if os.path.exists(NODE_APP_DIR):\n        print(f"'{NODE_APP_DIR}' already exists. Cleaning up first...")\n        clean_nodejs_app()\n\n    print(f"\
Setting up Node.js Express app in '{NODE_APP_DIR}'...")\n    os.makedirs(NODE_APP_DIR, exist_ok=True)\n    \n    # Create package.json\n    package_json_path = os.path.join(NODE_APP_DIR, PACKAGE_JSON_FILE)\n    with open(package_json_path, "w") as f:\n        f.write(PACKAGE_JSON_TEMPLATE.strip())\n    print(f"Created {package_json_path}")\n\n    # Install Express\n    print("Installing Express.js via npm...")\n    try:\n        # Ensure we run npm install in the correct directory\n        subprocess.run(["npm", "install", "express"], check=True, cwd=NODE_APP_DIR, \n                       capture_output=False, text=True)\n        print("Express.js installed successfully.")\n    except subprocess.CalledProcessError as e:\n        print(f"Error installing Express.js: {e}")\n        print(f"NPM output: {e.stdout}\
{e.stderr}")\n        sys.exit(1)\n\n    # Create server.js\n    server_file_path = os.path.join(NODE_APP_DIR, SERVER_FILE)\n    with open(server_file_path, "w") as f:\n        f.write(SERVER_JS_TEMPLATE.strip())\n    print(f"Created {server_file_path}")\n\n    print("\
Node.js Express app setup complete.")\n    print(f"You can now run the server using 'python src/manager.py --start'")\n    print(f"Access it in your browser at http://localhost:{PORT}")\n\ndef start_nodejs_app():\n    """Starts the Node.js Express server."""\n    if not os.path.exists(os.path.join(NODE_APP_DIR, SERVER_FILE)):\n        print(f"Error: Node.js app not found in '{os.path.abspath(NODE_APP_DIR)}'.\
"\\n              "Please run 'python src/manager.py --setup' first.")\n        sys.exit(1)\n\n    if not check_nodejs_npm():\n        sys.exit(1)\n\n    print(f"\
Starting Node.js Express server from '{os.path.abspath(NODE_APP_DIR)}'...")\n    print(f"Access it at http://localhost:{PORT}")\n    print("Press Ctrl+C to stop the server.")\n    try:\n        # Using npm start script defined in package.json\n        subprocess.run(["npm", "start"], cwd=NODE_APP_DIR)\n    except KeyboardInterrupt:\n        print("\
Node.js server stopped by user.")\n    except Exception as e:\n        print(f"Error starting Node.js server: {e}")\n\ndef clean_nodejs_app():\n    """Removes the generated Node.js application directory."""\n    if os.path.exists(NODE_APP_DIR):\n        print(f"\
Removing '{os.path.abspath(NODE_APP_DIR)}' directory...")\n        shutil.rmtree(NODE_APP_DIR)\n        print("Node.js app cleaned.")\n    else:\n        print(f"'{NODE_APP_DIR}' not found. Nothing to clean.")\n\ndef main():\n    parser = argparse.ArgumentParser(\n        description="A Python manager for Node.js Express applications.",\n        formatter_class=argparse.RawTextHelpFormatter\n    )\n    parser.add_argument("--setup", action="store_true", help=\n"Set up the Node.js Express application.\
"\\n"  - Creates 'node_app' directory.\
"\\n"  - Generates package.json and server.js.\
"\\n"  - Installs 'express' via npm."\n    )\n    parser.add_argument("--start", action="store_true", help=\n"Start the Node.js Express server.\
"\\n"  - Requires --setup to have been run first."\n    )\n    parser.add_argument("--clean", action="store_true", help=\n"Clean up the Node.js Express application directory.\
"\\n"  - Deletes the 'node_app' directory and its contents."\n    )\n    parser.add_argument("--check", action="store_true", help="Check if Node.js and npm are installed.")\n\n    args = parser.parse_args()\n\n    if args.setup:\n        setup_nodejs_app()\n    elif args.start:\n        start_nodejs_app()\n    elif args.clean:\n        clean_nodejs_app()\n    elif args.check:\n        check_nodejs_npm()\n    else:\n        parser.print_help()\n\nif __name__ == "__main__":\n    # Ensure script runs from project root for consistent pathing\n    if os.path.basename(os.getcwd()) == 'src':\n        os.chdir('..') # Go up to the project root\n    main()\n